// Next.js の型とGoogleフォントのインポート
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// グローバルCSSのインポート
import "./globals.css";


// Geist Sansフォントの設定
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


// Geist Monoフォントの設定
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// サイトのメタデータ
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// ルートレイアウトコンポーネント
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 子コンポーネントを描画 */}
        {children}
      </body>
    </html>
  );
}
